version: "3"

services:
  api:
    container_name: terraform-gcp-gce-8000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/src

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    tty: true

volumes:
  db_data:
